# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:  # job's name; every .circleci/config.yml file must have a job named build
    docker:  # executor of the underlying technology
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: continuumio/anaconda3
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            conda env create -f myenv.yml -n environment
            source activate environment

      - run: |
          cd ..
          chmod +x run.sh
          ./run.sh

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
